name: Build and Push Docker image

on:
  push:
    branches:
      - main  # ou "master", selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ğŸ§± 1. Cloner le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ğŸ‹ 2. Se connecter Ã  Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # âš™ï¸ 3. Builder et push lâ€™image
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aminefaw89/dev:latest